name: Run Tests

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  test:
    runs-on: ubuntu-latest  # Use a full Ubuntu VM instead of a container

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    -  name: Install Chrome
       run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Dependencies
      run: npm install
      working-directory: ./test  # Set working directory to 'test' since package.json is there

    - name: Start Web Server
      run: |
        python3 -m http.server 8000 &  # Run in the background
      working-directory: ./src  # Set working directory to 'test' since package.json is there

    - name: Run Tests
      run: npx mocha "test/**/*.test.js"


