name: Run Tests

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  test:
    runs-on: ubuntu-latest  # Use a full Ubuntu VM instead of a container

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Chrome & ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y chromium-chromedriver
        echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV
        echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV

    - name: Install Dependencies
      run: ls
      working-directory: ./test  # Set working directory to 'test' since package.json is there

    - name: Start Web Server
      run: |
        python3 -m http.server 8000
        sleep 5      # Give time for the server to start

    - name: Run Tests
      run: npx mocha "test/**/*.test.js"


