name: Run Tests

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  test:
    runs-on: ubuntu-latest  # Use a full Ubuntu VM instead of a container

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Chrome & ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y chromium-chromedriver
        echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV
        echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV

    - name: Install Dependencies
      run: npm install

    - name: Start Web Server
      run: |
        npm start &  # Modify this to match your actual start command
        sleep 5      # Give time for the server to start

    - name: Run Tests
      run: npx mocha "test/**/*.test.js"


